@host = https://test.ahdis.ch
### @host = http://localhost:8080


### FHIR Tutorial Step 7

### FHIR Tutorial send StructureDefinition TLeft1
POST {{host}}/r4/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tleft.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/r4/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tright.xml

### Post the StructureMap with transform included
POST {{host}}/r4/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./map/step7.map

### Post the StructureMap with transform included
POST {{host}}/r4/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./map/step7b.map

### FHIR Tutorial do the transform
POST {{host}}/r4/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step7
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./source/source7.xml

### FHIR Tutorial do the transform
POST {{host}}/r4/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step7b
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./source/source7.xml
