@host = https://test.ahdis.ch
### @host = http://localhost:8080


### FHIR Tutorial Step 10

### FHIR Tutorial send StructureDefinition TLeft
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tleft.xml

### FHIR Tutorial send StructureDefinition TLeft
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tleftinner.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tright.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-trightinner.xml


### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./map/step10.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step10
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./source/source10.xml