@host = https://test.ahdis.ch
### @host = http://localhost:8080


### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./memberof.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/memberof
Accept: application/fhir+json
Content-Type: application/fhir+json

{
    "resourceType": "Patient",
"maritalStatus" : {
    "coding" : [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
        "code" : "M",
        "display" : "married"
      }
    ]
  }
}


### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./stringtocoding.map


### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/stringtocoding
Accept: application/fhir+json
Content-Type: application/fhir+json

< ../qrtopat/qr.json


### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./stringtocodingwithcc.map



### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/stringtocodingwithcc
Accept: application/fhir+json
Content-Type: application/fhir+json

< ../qrtopat/qr.json



### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./quantity.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/qty
Accept: application/fhir+json
Content-Type: application/fhir+json

< ../qrtopat/qr.json


### Post the StructureMap with transform included
PUT {{host}}/matchbox/fhir/StructureMap/37238 HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./cast.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/cast
Accept: application/fhir+json
Content-Type: application/fhir+json

< ../qrtopat/qrext.json
