@host = https://test.ahdis.ch
### @host = http://localhost:8080


### FHIR Tutorial Step 2

### FHIR Tutorial send StructureDefinition TLeft
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tleft.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tright.xml

### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./map/step2.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step2
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./source/source2.xml
