@host = https://test.ahdis.ch
### @host = http://localhost:8080


### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./extension.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://basic.test/medication-request
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./source.json

