@host = http://test.ahdis.ch

### FHIR Tutorial Step 1

### FHIR Tutorial send StructureDefinition TLeft
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tleft.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./logical/structuredefinition-tright.xml

### Post the StructureMap
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./map/step1.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./source/source1.xml
