@host = https://test.ahdis.ch
### @host = http://localhost:8080


### FHIR Tutorial Step 5

### FHIR Tutorial send StructureDefinition TLeft
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tleft.xml

### FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tright.xml

### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./map/step5.map

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step5
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./source/source5.xml

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step5
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./source/source5b.xml


### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step5
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./source/source5.json

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step5
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./source/source5b.json