@host = https://test.ahdis.ch
### @host = http://localhost:8080

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./source/source1.xml

### FHIR Tutorial do the transform
POST {{host}}/matchbox/fhir/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/tutorial-step1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./source/source1.json


### Add Logical Model if not knwon FHIR Tutorial send StructureDefinition TLeft1
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tleft.xml

### Add Logical Model if not knwon FHIR Tutorial send StructureDefinition TRight
POST {{host}}/matchbox/fhir/StructureDefinition HTTP/1.1
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./logical/structuredefinition-tright.xml

### Post the StructureMap with transform included
POST {{host}}/matchbox/fhir/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ./map/step1.map



### DEBUG
GET {{host}}/matchbox/fhir/StructureDefinition?url=http://hl7.org/fhir/StructureDefinition/tutorial-left-1 HTTP/1.1
Accept: application/fhir+json

### DEBUG
GET {{host}}/matchbox/fhir/StructureDefinition?url=http://hl7.org/fhir/StructureDefinition/tutorial-right-1 HTTP/1.1
Accept: application/fhir+json

### DEBUG
GET {{host}}/matchbox/fhir/StructureMap?url=http://hl7.org/fhir/StructureMap/tutorial-step1 HTTP/1.1
Accept: application/fhir+json

###
DELETE {{host}}/matchbox/fhir/StructureDefinition?url=http://hl7.org/fhir/StructureDefinition/tutorial-left-1 HTTP/1.1
Accept: application/fhir+json

###
DELETE {{host}}/matchbox/fhir/StructureDefinition?url=http://hl7.org/fhir/StructureDefinition/tutorial-right-1 HTTP/1.1
Accept: application/fhir+json
